### ISSUE TITLE
Add skills to tasks

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1042]
# Problem

We want users to be able to add and remove skills to/from tasks

## Subtasks

- [x] Assigned skills should be visible on task card - #1045
- [x] Add/remove UI should be present on the task page - #1045
- [x] Add/remove UI should be present on the task new page? - #1046
- [ ] Add/remove UI should only be usable by project contributors or higher - #1043 

I think the last one, considering how much harder it is to deal with, might be OK to punt for a later time. I'm not really sure, but I think it's worth discussing.
