### ISSUE TITLE
Rewrite skill button so only authenticated users can trigger the remove action

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1043]
# Problem

Currently, with the skill button, there is no check to see if the user hovering/clicking it can remove the skill from whichever related parent.

We could technically deal with this at a higher level, route for example, but due to the hover effect also being applied, It would be very complicated to do it that way. We need to either use the session service directly, or pass in a `canRemove` flag into the component. The later is preferable, since it provides more flexibility in what that flag is actually determined from

We do not need this for project skills, since the place where that component is rendered for project skills is a route only accessible by owners.

For task skills, however, any contributor should be able to toggle skills.

## Subtasks

- [ ] Pass in `canRemove` flag into `skill-button`
- [ ] Hover effect should work depending on the `canRemove` flag
- [ ] `remove` action should work depending on the `canRemove` flag

**Comment by JoshSmith** [comment]
I think this actually needs rewritten to *not* show the skill buttons unless in an editing state, and otherwise show a `skills-list`.

**Comment by begedin** [comment]
@JoshSmith I missed your comment. I absolutely agree. It does sound like a better approach.

**Comment by JoshSmith** [comment]
I think this deserves some more discussion and clarification still, since it seems like we've developed several competing UIs, and I'd like to do some work to clear some of those up and simplify them.

This really needs design-level clarification right now.
