### ISSUE TITLE
Rewrite skill-button so there's no unnecessarily deep HTML

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1044]
# Problem

Right now, the `skill-button` is a `div` which, internally, renders a single, albeit complicated `button` tag.

We should rewrite it so that component itself is a `button` and all the associated bindings are determined at the component root level

## Subtasks
- [x] Remove `button` "wrapper" tag from the `skill-button.hbs
- [x] Add `tagName: button` to `skill-button.js`
- [x] Reimplement class and action binding at the `.js` instead of the `.hbs` level

This task probably requires a decent amount of ember component knowledge, but with guidance, should not be too complicated.
