### ISSUE TITLE
Clean up task assignment

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1064]
# Problem

We have a number of things to clean up in the task assignment.

## Subtasks
- [ ] Possible junk code needs to be hunted down and removed
- [ ] Add a component test for `user-select`
- [ ] Add an acceptance test
- [ ] Fix possible issues with Mirage (probably out of sync)
