### ISSUE TITLE
Add a /reset-password route and component

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1125]
# Problem

We need a UI to perform a password reset action

## Subtasks
- [ ] Add `/reset-password/:token` route
- [x] Add `components/password/reset-password`
- [x] Component should have a form two password fields, for password and password confirmation
- [x] On submitting the form, an action should trigger
- [ ] Route should handle action by sending an API `POST /reset-password` request with the following data: 

```Javascript
{
  value: token // from query param,
  password,
  password_confirmation
}
```

- [x] on success, route should log user in with new credentials and show a flash with a success message
- [ ] on a 422 failure, it should indicate that the passwords do not match

# Notes

We can use mirage to do this until https://github.com/code-corps/code-corps-api/issues/498 is done. Otherwise, it's partially blocked by that set of API issues.

I would not consider it blocked by #5, though, since there is nothing preventing us from displaying an unstyled form for now. The UI won't be hooked up with the rest of the app immediately.

**Comment by JoshSmith** [comment]
Thinking we may want to call this `/password/reset`

**Comment by snewcomer** [comment]
@JoshSmith What were you referring to?  The route name being called `password/reset`?

**Comment by JoshSmith** [comment]
@snewcomer yeah the route name being called `password/reset`. Not sure about API. What do you think?

**Comment by snewcomer** [comment]
@begedin #1231 is pretty close now.  One remaining item is to log in user with new credentials.  How do you think we should go about doing this?

**Comment by begedin** [comment]
During password reset, you have access to the email and the typed in password (and confirmation). At that point, it should be a matter of calling session to authenticate.

You can see how it's done in the login form and do something similar:


```javascript
authenticate() {
  set(this, 'isLoading', true);

  let credentials = this.getProperties('identification', 'password');

  get(this, 'session').authenticate('authenticator:jwt', credentials).catch((reason) => {
    set(this, 'isLoading', false);
    set(this, 'errors', reason.error || reason);
  });
}
```

You can ignore the `isLoading` part for now, as well as error handling. Just get the email and the password the user typed in and call 

```javascript
get(this, 'session').authenticate('authenticator:jwt', { identification: email, password: password });
```

once the reset task is successfully completed.

**Comment by snewcomer** [comment]
@begedin for your review! Almost ready to go.  https://github.com/code-corps/code-corps-ember/pull/1231
