### ISSUE TITLE
Add a /forgot-password route and component

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1126]
# Problem

We need UI to request a password reset email in case the user forgot their password

## Subtasks
- [ ] Add `/forgot-password` route
- [x] Add `components/password/forgot-password`
- [x] Component should have a form with an email field
- [x] On submitting the form, an action should trigger
- [ ] Route should handle action by sending an API `POST /forgot-password` request with the following data: 

```Javascript
{
  email
}
```

- [x] on success, route should redirect to index with a flash message indicating an email has been sent. The message should be vague. We don't want phishing to happen. Something like

"If your email is associated with an account registered here, a password reset link has been sent to it."

# Notes

We can use mirage to do this until https://github.com/code-corps/code-corps-api/issues/498 is done. Otherwise, it's partially blocked by that set of API issues.

I would not consider it blocked by #5, though, since there is nothing preventing us from displaying an unstyled form for now. The UI won't be hooked up with the rest of the app immediately.

**Comment by JoshSmith** [comment]
Thinking we may want to call this `/password/forgot`
