### ISSUE TITLE
Launch 1.0

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#114]
**Design**
- [x] Design signup form #1
- [x] Design projects list page #8
- [x] Design landing page #117
- [x] Design adding skills page #6
- [x] Design project page #10
- [x] Design post page #15

**API Development**
- [x] Add Category https://github.com/code-corps/code-corps-api/issues/267
- [x] Add ProjectRole https://github.com/code-corps/code-corps-api/issues/270
- [x] Add ProjectSkill https://github.com/code-corps/code-corps-api/issues/271
- [x] Add UserInterest https://github.com/code-corps/code-corps-api/issues/274
- [x] Figure out how to get fuzzy ngram skill searching working with elastic search
- [ ] _In Progress_ Make sure email is not exposed from API unless publicly available https://github.com/code-corps/code-corps-api/issues/243

**HTML/CSS**
- [x] Implement signup form changes #115

**Ember Development**
- [x] Add image uploading for users, organizations, and projects #109
- [x] _In Progress_ Implement projects list page
- [x] _In Progress_ Implement onboarding flow
- [x] Implement adding skills page #7
- [x] _In Progress_ Allow users to join projects #120
- [ ] _In Progress_ Implement landing page

**Comment by JoshSmith** [comment]
Closing because this is no longer useful. Separate tasks in milestones cover this better.
