### ISSUE TITLE
Extract project join status from project-card component into a separate component

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1181]
# Problem

The logic for the project status/join button in the project card template is highly complex. We could simplify it by extracting a part.

The following code:

```handlebars
{{#if currentProjectMembership.isLoaded}}
  {{#if (eq currentProjectMembership.role 'pending')}}
    <button class="clear small" disabled>Request sent</button>
  {{else}}
    <button class="clear small" disabled>Member</button>
  {{/if}}
{{/if}}

{{#unless currentProjectMembership}}
  {{project-join-modal project=project skills=projectSkills}}
{{/unless}}
```

should be replaced with the equivalent of:

```handlebars
{{#if currentProjectMembership}}
  {{project-membership-status membership=currentProjectMembership}}
{{else}}
  {{project-join-modal project=project skills=projectSkills}}
{{/if}}
```

## Subtasks

- [ ] Implement component
- Write integration tests for component
  - [ ] If current project membership is not loaded, it renders nothing
  - [ ] If current project membership is loaded and role is pending, it renders the "Request sent" button
  - [ ] If current project membership is loaded and role is something else, it renders the "Member" button
  - [ ] A page-object should be written for these tests
- [ ] Replace code with component
- Add integration tests for project card component
  - [ ] If there is a current project membership, it renders the project-membership-subcomponent
  - [ ] If there is no current project membership, it renders the project-join-modal subcomponent
  - [ ] The project-card page object will need to be expanded with two new properties for this
