### ISSUE TITLE
ember-dragula: Submit PR to remove component lifecycle deprecation

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1204]
# Problem

We are currently using ember-dragula for our task board. 

At the moment, there is a deprecation in ember triggered by this addon, due to component lifecycle hooks.

https://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks

I've created an (issue in their repository](https://github.com/kalcifer/ember-dragula/issues/27)

## Subtasks
- [ ] If the issue has not been resolved yet, submit a PR to the ember-dragula repo
- [ ] Once the issue has been resolved and the change released as a new version, update the dependency here
- [ ] If the deprecation is gone, we can consider this issue closed.

## References

Progress on: #
