### ISSUE TITLE
emberx-select: Update from 3.0.0 to newer to resolve deprecation

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1205]
# Problem

We are currently using emberx-select for some of our select dropdowns. 

At the moment, there is a deprecation in ember triggered by this addon, due to component lifecycle hooks.

https://emberjs.com/deprecations/v2.x/#toc_arguments-in-component-lifecycle-hooks

This issue has already been fixed on master, but not officially released yet. At the moment, it's just a deprecation, but we should keep track and update as soon as it's available

## Subtasks
- [ ] Update emberx-select to any new version past 3.0.0
- [ ] If the update resolves the above deprecation, mark this issue as closed
- [ ] If the update does not resolve the deprecation, update this description to indicate the currently installed, but unresolved version of the addon.

**Comment by JoshSmith** [comment]
Done now.
