### ISSUE TITLE
ember-cli-deploy-sentry: Update from 0.5.1 to newer to remove deprecation

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1206]
# Problem

We are currently using ember-cli-deploy-sentry.

At the moment, there is a deprecation in ember triggered by this addon, due to using Promise instead of RSVP.

This issue has already been fixed on master (I've submitted a PR and it has been merged), but not officially released yet. At the moment, it's just a deprecation, but we should keep track and update as soon as it's available

## Subtasks
- [ ] Update ember-cli-deploy-sentry to any new version past 0.5.1
- [ ] If the update resolves the above deprecation, mark this issue as closed
- [ ] If the update does not resolve the deprecation, update this description and title to indicate the currently installed, but unresolved version of the addon.
