### ISSUE TITLE
Deprecation: Native dom helpers should not be used as globals in tests anymore

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1207]
# Problem

Using native dom helpers as globals is now deprecated in our tests. Instead, we should add a new dependency to our app and import these helpers from it in any tests that need it.

We are leaning away from these anyway, due to relying on ember-cli-page-object, but there are still a couple of places where we do use them.

## Subtasks
- [ ] Install depdencency https://github.com/cibernox/ember-native-dom-helpers
- [ ] Search through our tests for usage of the `find`, `click`, `fillIn`, `visit` and other global functions in this group. Careful not to mistake them for the identically named functions provided by `ember-cli-page-object`. The culprits we need to fixed are likely used as globals, in tests, directly.
- [ ] In any module that uses them, import them using `import { visit, click, find, fillIn } from 'ember-native-dom-helpers';`

**Comment by JoshSmith** [comment]
@begedin to what extent would it be better to simply replace whatever we were doing with page objects (shouldn't be a ton of those remaining) rather than resolve these deprecations specifically? Seems like using page objects would implicitly solve this issue.

**Comment by begedin** [comment]
It would take longer, but from what I can tell, not much longer.

That being said, in the window between the deprecation and the outright removal of globals, we're risking someone using them again and triggering the deprecation again. I guess if we're careful with nothing let those through PR reviews, we should be safe.
