### ISSUE TITLE
Add loading state to volunteer-headshot component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#1221]
# Problem

The `volunteer-headshot` should have some loading states for async data.

## Subtasks
- [ ] Add a light gray background for the image as a placeholder, until loaded (keeping in mind that a user may have a transparent PNG, so the background shouldn't remain gray)
- [ ] Add a light gray rectangular area for the user's name as a placeholder, until loaded
- [ ] Add a light gray rectangular area for the user's role as a placeholder, until loaded

**Comment by alistermada** [comment]
Is this okay? This was shot while using the mirage fake API with 4 sample users.
![ccshot](https://cloud.githubusercontent.com/assets/12993334/25577853/8c48d5b4-2e93-11e7-8067-257019a64d99.jpg)

**Comment by JoshSmith** [comment]
@alistermada wow sorry for super long delay here. Missed this notification somehow. This looks perfect! Are you ready to submit a PR for it?

**Comment by alistermada** [comment]
Sorry it's been a while since I worked on this fix. I still need to figure out how to change the tests to make them pass this new code.

**Comment by JoshSmith** [comment]
If you want to push up the changes, then I can give some pointers on how to accomplish that.

**Comment by JoshSmith** [comment]
Opening a PR is a good first step so we can start the conversation around it.
