### ISSUE TITLE
Add route to handle successful github authentication

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1264]
# Problem

Component created in #1263 will be a link. Clicking this link will send the user to github, where they will be able to, with their signed in github account, authorize codecoprs to connect. Once that's done, the user will be redirected back to codecorps, to a route we specified.

This route should be `/github/`

In the model hook, the route should expect a `code` query parameter. The model hook should post this `code` parameter to our API and expect an OK response of some sort.

```
POST { code: code }
```

_In the background, the API will `POST` the code to github, along with a `CLIENT_ID` and a `CLIENT_SECRET` and receive back and `auth_token` to store and associate with the current user. The API should reply to the client with a JSON containing the updated current user_

Once that's done, and the API responds, in `afterModel`, we should push the user response into the store and set it into our session service as `currentUser`. The user should then redirect to the profile route.

## Subtasks
- [ ] Add route with `model` and `afterModel` hooks
- [ ] Add acceptance test for the successful flow. Use mirage to mock a server response. Test should ensure:
  - [ ] route posts to server with proper code
  - [ ] current user is properly updated in the schema
  - [ ] flash message is displayed

## References

NOTE: This is not blocked by #1263. It can be worked on in paralel.
