### ISSUE TITLE
Write module which generates a random string

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1265]
# Problem

- #1263 Gives us a component which navigates to github for authentication
- #1264 Gives us a route which handles a successful authentication and finalizes the flow using our API

To prevent cross site forgery, we need to add a `state` parameter to the link in #1263. This parameter is then returned by github and hits our route in #1264 as a query param. We will then be able to check if the one we sent and the one we received back are identical.

We need a service module which generates this string and somehow persists it across sessions, associated to the signed in user.

**We should discuss and decide on the persisting method.** It could be local storage, or potentially an API request (meaning the API would have an action which generates the scope and somehow associates it with the user, possibly even on a DB level). The API option would certainly be safer.

## Subtasks
- [ ] Write `github-state` service:
  - [ ] Internally dependant on the `current-user` service
  - [ ] has `generate` function crates a persisted random string tied to the current user. 
  - [ ] has a `validate(state)` function which takes the parameter and compares it to the stored state tied to the current user. Returns true if the two are identical, false otherwise.
- [ ] Write unit tests for the service, ensuring the two methods work. Use mirage/pretender to mock server requests if there are any. If we opt for a localStorage/cookie based approach, then we need to figure out ways to mock that.

## References

Dependant on #1263 and #1264, but not blocked by them. Can be worked on in parallel.

**Comment by begedin** [comment]
@JoshSmith Could use your thoughts on best way to generate the state. 

I feel the API approach is the safest, but something with local storage is doable. The problem is that the generated string somehow needs to be stored across browser sessions, since we leave our site and come back later. We can work on most of this without an answer, but will have to agree on something in the end, before the feature can work.

**Comment by JoshSmith** [comment]
I would prefer the API-only approach re: storage.

**Comment by begedin** [comment]
From #1282, you've reviewed it as if it's getting merged this way. If we're going API only, then the whole PR needs to be rewritten and we need to add an API PR which

- adds a `github_state` field to the user
- adds a module which generates a random string for it (we can just use crypto or something)
- adds an endpoint which returns that state, or updates the user and returns the updated user

This, client side would then

- first hit our API to get the state
- then redirect to githubs authorize route
- then get redirected back to a client route, with `state` and `code` as query params
- then send the two again to our API
- API would take the state, check it against the stored user state
  - if they match, continue, if they fail, return an error
- if the states match, the API takes the code and uses it to generate an auth token, saves it to the user and renders updated user
- client handles success an failure similarly as it does now, except checking state/failure success is now an extra API call

This is doable, but that being said, the client-side approach, using local storage, or more accurately, using the persisted storage capacities of `ember-simple-auth`, which are intended for cases like this one, is more or less almost completely.

Most examples I'm seeing generate and store the state in the browser session.

Due to this, I think our most cost effective course right now is to continue with this, almost done implementation. Switching to one that's API-based later should not be problematic.
