### ISSUE TITLE
Implement cross site forgery protection

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1266]
# Problem

Once #1263, #1264 and #1265 are done, we should implement cross site forgery protection.

## Subtasks
- [ ] The component in #1263 should set it's `state` property from the #1265 `github-state` service `generate()` function.
- [ ] The `model` hook  in the route from #1264 should check the `state` using the `validate(state)` function, before posting the `code`. If the check fails, it should redirect to root, with an error flash saying something went wrong.
- [ ] There should be an addition to the integration test for the `github-connect-link` component. The addition should test that the `href` contains the `proper` state when mocking the `github-state` service.
- [ ] There should be an additional acceptance test for the route in #1264, which ensures proper redirection happens when `state` validation fails. Again, we can mock the `github-state` service for this.

## References

Blocked by: #1263, #1264, #1265
