### ISSUE TITLE
Add github-repository-select component

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1273]
# Problem

We need to add a component to the project, which allows selecting a github repo when creating a task.

If a github repo is selected, that task is then created alongside an issue on github and the two are then kept in sync by our backend.

## Subtasks
- [x] Add `githubRepo` relationship to task
- [x] Create component
- [x] Add integration tests for the component
- [x] Add component to `tasks.new` route
- [x] Add acceptance test to ensure component works in the route (task is saved associated to github repo)
