### ISSUE TITLE
Add github service, with getRepositories function

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1275]
# Problem

We need a github service, which provides data for github integration using the current user's auth token. 2 functions are needed, `getRepositories`, and `getIssues`.

This issue handles the `getRepositories` function.

The function should either accept a current user as a parameter, or have the current user service as an injected dependency, to get it that way.

The function should return all repositories from the github API and return them as a collection in the format `{ repositoryName, githubId }`.

## Subtasks
- [ ] Add `/services/github.js` if it doesn't already exist
- [ ] Add `getRepositories` with described behavior to the service
- [ ] Add unit tests for the function

**Comment by begedin** [comment]
This is now obsolete
