### ISSUE TITLE
Add github service, with getIssues function

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1276]
# Problem

We need a github service, which provides data for github integration using the current user's auth token. 2 functions are needed, `getRepositories`, and `getIssues`.

This issue handles the `getIssues` function.

The function should accept a project as a parameter.

The function should use the project's githubId, which is a repository ID to return all open issues for that repository from the github API and return them as a collection in the format `{ issueName, githubId }`.

## Subtasks
- [ ] Add `/services/github.js` if it doesn't already exist
- [ ] Add `getIssues` with described behavior to the service
- [ ] Add unit tests for the function

**Comment by begedin** [comment]
This is now obsolete
