### ISSUE TITLE
Add github-repository-select component to project.settings.profile page

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1277]
# Problem

A project owner, if their account is connected with github, should be able to assign a github repository to the project.

To that purpose, we should add the `github-repository-select` component to the the `project.settings.profile` page, if the conditions are met:

  - current user is connected to github (they have a github auth token)
  - current user is project owner

The route should provide the data to the component, but this should be done through a service implemented in another issue.

When the component triggers the select action, the project should be assigned the github id and saved.

## Subtasks
- [ ] Render `{{github-repository-select}}`
- [ ] Select data should be provided by service from #1275
- [ ] If the project is already connected to a github repo (meaning it has a githubId), that repository should be preselected.
- [ ] When action is sent by the component, update project with github id and save it.
- [ ] Add acceptance test

**Comment by begedin** [comment]
The requirements here have greatly changed from what was originally imagined and that needs to be done is covered by #1273 Closing this
