### ISSUE TITLE
Add github-issue-select component to the project.tasks.new page

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1278]
# Problem

A user, when creating a task, if the project is connected to github, should be able to assign a github issue to the task.

To that purpose, we should add the `github-issue-select` component to the the `project.tasks.new` page, if the conditions are met:

  - project is connected to github (it has a github id)

The route should provide the data to the component, but this should be done through a service implemented in #1276 

When the component triggers the select action, the task should be assigned the github id.

## Subtasks
- [ ] Render `{{github-issue-select}}`
- [ ] Select data should be provided by service from #1276
- [ ] When action is sent by the component, update unsaved task with github id.
- [ ] Add acceptance test for the task creation process where a github issue was selected

**Comment by begedin** [comment]
The requirements here have greatly changed from what was originally imagined and that needs to be done is covered by #1273 and its PR, #1295
