### ISSUE TITLE
Umbrella Issue: Project GitHub integration flow

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1331]
# Problem

This issue should serve as an umbrella issue to discuss and implement the full GitHub integrations flow for connecting GitHub repositories to a Code Corps project.

### Project integrations page

- [x] Each project has an integrations tab, only visible to the project owner
- [x] The integrations tab has a GitHub section
- [x] Show if the user is already connected to GitHub and:
  - [x] If not, display a button to connect their GitHub account.
  - [x] If so, display a button to add the project GitHub integration.

The user's GitHub `id` is used to match the webhook to the `User` and the originating `Project`. Once the user has returned from GitHub, we can use the originating project's `id` to redirect the user to the integrations tab on the project page. Unfortunately, GitHub does not currently have a better redirect flow to the requesting application.

### Redirect to GitHub

- [x] Creates a `GitHubAppInstallation` record on the API (see model details below)
- [ ] Redirects to GitHub
   - the user selects where to install (user or organization)
   - the user selects repositories
   - the user clicks install

#### Webhooks

- [x] Receive and handle webhook from GitHub API of installation event with id
  - [x] Find existing `GitHubAppInstallation` for the GitHub user
  - [x] Requests repositories from GitHub's `https://api.github.com/installation/repositories` endpoint using the GitHub app's installation token. Use these repositories to create or update `GitHubRepo` records and `ProjectGitHubRepo` records.
- [x] Listen for `installation_repositories` webhook which will notify you of added/removed repositories on an installation. Again, use this to create or update `GitHubRepo` records and `ProjectGitHubRepo` records.

### Back to client process

- ~~User is redirected back to Code Corps `/integrations/github`~~
- ~~Query parameters should contain an `installation_id`. Retrieve the user's _only_ `GitHubAppInstallation` with a `status` from the API.~~

Instead, we opted to open the github page in a new window and instruct the user to come back and refresh. Simpler to deal with to begin with. Can improve on later.

#### Handling the statuses and other edge cases

There are various `status` types that we can get back from the API depending on where the user was in the installation process.

- ~~`initiated_on_code_corps` - we haven't received the webhook yet. Ideally we would ping the API for changes or wait for a channel to complete, but for now, we can have the user click refresh until the application fetches new model data. We should also warn them not to close their browser or navigate away.~~
- ~~`processing` - we still need to fetch all the repos from the API to display on the project integrations page. As above, ideally we would ping the API for changes or wait for a channel to complete, but for now, we can have the user click refresh until the application fetches new model data.~~
- ~~`processed` - Redirect them to the project integrations page.~~
- ~~`initiated_on_github` - we received an `installation` webhook with a matching user, but an installation was never created on Code Corps. Edge case for now, but can be handled by asking them to identify a project where they are an `owner` in order to complete the process.~~
- ~~`unmatched_user` - when we receive a webhook but there is no such Code Corps user with the given GitHub `id`. Edge case for now. This should only happen when the installation was initiated on GitHub. We can handle this by asking a user to connect with GitHub after the fact, and in the meantime matching the installation up to that user. Once the user has connected, we can move the status of the installation to `initiated_on_github` so they can pick a project.~~
- ~~Missing `installation_id` in the query params. Edge case for now, but can be handled by providing an error message on the `/integrations/github` page specifically.~~

**This has been made simpler instead and split up into separate fields, since we track multiple different statuses here**

#### Redirecting to the project integrations page
- ~~The `GitHubAppInstallation` record will have a `Project` relationship; we should redirect to that project's "integrations" tab.~~
- ~~On the integrations tab, we list the `GitHubRepo`s for the project via the `ProjectGitHubRepo` relationships. None of them should be followed yet. The user can refresh~~
- ~~There could be a case where the webhook has not been handled yet, so we may want to show a status for each, with an option to refresh~~
- ~~Next to each repo is a button to connect the project with that repo. This creates a `ProjectGitHubRepo` on our API and we start handling webhooks. We call this "following a repo". (see further notes on the need to create a separate model here).~~

Again, simplified a good amount. We list installations with the option to install more.

For each installation, if there is an `OrganizationGithubAppInstallation`, we display that installation as connected and list repos for that installation.

For each repo, if there is a `ProjectGithubRepo`, we display that repo as connected, with the option to remove (deletes `ProjectGithubRepo`). If the repo is not connected, there is an option to connect (creates `ProjectGithubRepo`).

#### Webhooks

See above for some specific webhook flows, and the discussion below of `GitHubEvent`.

Once a project is connected, we use webhooks to determine which projects will receive changes from `issue` and `issue_comment` events.

##### `GitHubAppInstallation`

- `user` - the user who initiated the install. Matched to a user by the `sender` `id` in the `installation` webhook.
- `originating_project` - the project where the installation was initiated. Used to redirect back to the project’s integrations page to complete the installation process. There's not necessarily a `project` for a given installation, as an installation really exists only on a per-GitHub account basis for a given GitHub app.
- `state`
  - `initiated_on_code_corps` - the user clicks from Code Corps’ UI to go to GitHub and install
  - `initiated_on_github` - we receive an `installation` webhook with a matching user, but an installation was never created on Code Corps
  - `processing` - when the installation webhook is received, was matched, and is now processing
  - `processed` - the integration process is completed from the perspective of there being an installation on the project.
  - `unmatched_user` - when we receive a webhook but there is no such Code Corps user with the given GitHub `id`

A user can only have one `GitHubAppInstallation` in the `initiated` state at any given time. This prevents a case where a user could unintentionally have two pending installations at the same time for different projects – we wouldn’t know which project to relate everything to by default.

##### `GitHubEvent`

- `action` - under the `action` key in the payload, e.g. `created`
- `source` - application, application oauth, user oauth
- `status`
  - `errored`
  - `ignored`
  - `processing`
  - `processed`
  - `unhandled`
  - `unprocessed`
- `type` - can be matched to either the `"X-GitHub-Event"` HTTP header or one of the JSON keys in the payload, e.g. `installation` or `issue`

Explicitly ignore some events with reasoning; we can just log the ignored actions.

##### `GitHubRepo`

- `github_id`
- `github_account_id` - the owner account’s GitHub `id`
- `github_account_login` - the owner account’s GitHub username
- `github_account_avatar_url`
- `github_account_type` - e.g. `Organization` or `User`

##### `ProjectGitHubRepo`

- `github_repo`
- `project`
- `following` - whether the repo is currently being followed by the project. When a user selects repos in the GitHub installation process manually, we will auto-follow all of the repositories.

#### Controllers

- [x] `GitHubAppInstallation` has `:create`, `:show`, `:index` actions at a minimum (`:index` for filtering by the user's installation, or we could have a special endpoint to return the latest relevant one as explained above).
- [x] `GitHubRepo` with `:index` (for filtering) and `:show`. 
- [x] `ProjectGitHubRepo` `:index`, `:show`, `:create`, `:delete`

**Comment by begedin** [comment]
Just to recap, so you can confirm if I'm seeing this correctly:

# The connection process

A regular contributor will connect with github.

A project owner will have to first connect with github and then also connect their project with github (which installs the CodeCorps github app to one or more of the repos that github user has proper access to).

# Further options

Once the connection process id done

- If something happens on github, we get a webhook, identify what happened and decide what we're doing about it
- If something happens on codecorps, we decide if we want to do something on github
- We can do this on behalf of a connected user on a connected repo, provided that github user is able to do it on that github repo
- We can do this using the app's identity itself, if there's no user to do it as, or if the user does not have access to do it on github

**Comment by begedin** [comment]
Also a possible bit I'm not completely understanding:

>`ProjectGitHubRepo` model - a through association between a `Project` and a `GitHubRepo`

I'm not really sure we need this. It would imply that it has potential to be a many-to-many relationship. I don't think we should allow multiple code corps projects to connect with the same github repo. That's something that would be extremely difficult to deal with as we add features.

Instead, it should suffice for the `GitHubRepo` to simply belong to a project (nullable). 

Or am I no understanding and you simply want a clear cut between data from github we store locally and our own data, meaning `GitHubRepo` and `ProjectGitHubRepo` are 1-1 and we simply store the entity in two parts.

**Comment by JoshSmith** [comment]
I do think we want the option of an `m:n` relationship between `Project` and `GitHubRepo`. It would be harder to _prevent_ someone from unintentionally making this happen than it would be to fan updates coming in from a GitHub repo's webhook appropriately to each awaiting project.

That assumption also assumes the world is not as messy as it really is. I can totally see how the `code-corps/design` repo could be connected to two separate projects on here. And I would absolutely prefer it be possible.

I suspect perhaps you're overestimating the work involved in making that work. To my mind, it comes for free with the default work of preventing duplicate data when receiving GitHub webhooks. We'll need to be tracking with some granularity what events have been processed, and be fanning them out only when necessary.

**Comment by JoshSmith** [comment]
The biggest points of concern I have right now revolve around these points:

> - We can do this on behalf of a connected user on a connected repo, provided that github user is able to do it on that github repo
> - We can do this using the app's identity itself, if there's no user to do it as, or if the user does not have access to do it on github

It seems possible that a connected user on a connected repo does not, according to the integration, actually have write access to it. We may need an OAuth token for a user that is _not_ the OAuth token for the GitHub app installed on the project.

I need to test this to verify whether a user with an OAuth token for the GitHub app can write to that (public) project, even if they're not connected with the project in any way.

**Comment by JoshSmith** [comment]
The `UserGitHubInstallation` is necessary to know how to handle the webhook _and then_ how to redirect the user when they return to Code Corps from GitHub. GitHub's flow does not really consider the case of someone installing the integration from outside GitHub, as of this writing. We have to do some work to match up an installation that could have come from anywhere.

**Comment by JoshSmith** [comment]
What we may be able to do is simplify to a `GitHubAppInstallation` that `has_one` user, and then use the GitHub user id in the `sender` portion of the webhook (the person who requested it) to match to the indexed `github_id` column on the user and thus relate it as a `1:1` once the webhook resolves.

**Comment by JoshSmith** [comment]
As for everything you wrote following this:

> What I'm not sure is if the user is able to do things through the app which they would not normally be able to do. My guess is, as the user applies to join a project on CodeCorps.org, if they are github connected, we'd need to handle their application to associated github repos as well, and approve them as their membership is approved.

I think you may have misunderstood the relationship between a user and a GitHub app installation. We don't want the CC project to _need_ to add people as contributors to their repository just to comment on issues. The default model for most projects _on GitHub itself_ is to have the users submit pull requests without having any sort of actual write access. The surface area of the administration is relatively low compared to the surface area of contributors.

**Comment by JoshSmith** [comment]
So one point of clarification is that there are _three_ possible ways of interacting with GitHub:

- As a user with an `access_token` from an OAuth app to perform actions on behalf of the user
- As a user with an `access_token` from a GitHub app to perform actions on behalf of the user
- As the GitHub app's installation with a token used to perform actions on behalf of the app (or on behalf of a user who does not have a GitHub account)

**Comment by JoshSmith** [comment]
GitHubAppInstallation
- `user` - the user who initiated the install. Matched to a user by the `sender` `id` in the `installation` webhook.
- `originating_project` - the project where the installation was initiated. Used to redirect back to the project’s integrations page to complete the installation process.
- `state`
  - `initiated_on_code_corps` - when the user clicks from Code Corps’ UI to go to GitHub and install
  - `initiated_on_github` - when we receive an `installation` webhook where a user matches, but an installation was never created on Code Corps
  - `processing` - when the installation webhook is received, was matched, and is now processing
  - `unmatched_user` - when we receive a webhook but there is no such Code Corps user with the given GitHub `id`

A user can only have one `GitHubAppInstallation` in the `initiated` state at any given time. This prevents a case where a user could unintentionally have two pending installations at the same time for different projects – we wouldn’t know which project to relate everything to by default.


GitHubEvent
- `action` - under the `action` key in the payload, e.g. `created`
- `source` - application, application oauth, user oauth
- `status`
  - `errored`
  - `ignored`
  - `processing`
  - `processed`
  - `unhandled`
  - `unprocessed`
- `type` - can be matched to one of the json keys in the payload, e.g. `installation` or `issue`

Explicitly ignore some events with reasoning; we can just log the ignored actions.


GitHubRepo
- `github_id`
- `github_account_id` - the owner account’s GitHub `id`
- `github_account_login` - the owner account’s GitHub username
- `github_account_avatar_url`
- `github_account_type` - e.g. `Organization` or `User`


ProjectGitHubRepo
- `github_repo`
- `project`
- `following` - whether the repo is currently being followed by the project. When a user selects repos in the GitHub installation process manually, we will auto-follow all of the repositories.

GitHub app integration
	When going to install, create `GitHubAppInstallation` and set `state` to `initiated`
	When installation webhook received, set `GitHubAppInstallation`’s `state` to `processing`

**Comment by begedin** [comment]
This part:

> Redirect to GitHub
>- Creates a GitHubAppInstallation record on the API (see model details below)
>  - Redirects to GitHub
>    - the user selects where to install (user or organization)
>    - the user selects repositories
>    - the user clicks install

We'll have to navigate to the github URL programmatically, which is has potential to be a pain in tests. It's not hugely important, but just an observation

Also, there may be a case where the installation was already created, but the process was aborted on the redirected page, in which case there should be a button/link to just go straight to the github page.

> As a user with an access_token from a GitHub app to perform actions on behalf of the user

This one is slightly unclear to me

- As a CodeCorps user, in which scenario do I get such a token?
- Where is this token stored, compared to the one receieved through my going through the initial github connect process.
- Will the backend do anything different when using this token, compared to using the oauth token I got through GitHub connect.

Outside of this, everything else looks good.

**Comment by LennonR** [comment]
Mixpanel Tracking Ideas:

1. Loads integrations tab (properties: project_name, project_id)
2. Clicks connect to github button (properties: project_name, project_id)
3. Github connection successful (properties: project_name, project_id)
4. Github connection failed (properties: failure_reason, project_name, project_id)
5. Clicks add project Github integration button (properties: project_name, project_id)
6. Github project integration successful (properties: project_name, project_id)
7. Github project integration failed (properties: failure_reason, project_name, project_id)

Questions:

1. How does the project selection happen when you choose to add a project?  Does it take you to github and you choose from your projects?  Or is there a UI on code corps that lists projects?
2. Is there the option to disconnect/remove a project or a github installation, post connection/installation?
3. Once you've connected a project, what has changed about the UI?  What can you now do on Code Corps that you couldn't do before?

**Comment by JoshSmith** [comment]
> 1. How does the project selection happen when you choose to add a project? Does it take you to github and you choose from your projects? Or is there a UI on code corps that lists projects?

You go to GitHub and then choose a user or organization account where you have admin access, and then repositories within those. GitHub doesn't provide a way for us to list what they do, and the expected flow is that this choice is made on GitHub. If you wanted to connect a project to say the `code-corps` organization and the `JoshSmith` account both, then you'd have to install it twice. Each would be a separate installation of the integration.

From there, though, an installation doesn't necessarily match up 1:1 with a project. That same installation can be used across projects. Instead, you use the installation within a project to "follow" 1:n GitHub repositories.

I know it's a bit confusing, and we'll probably have to do some tweaking so it makes sense to the user. We're a bit bound by GitHub's choices here.

> 2. Is there the option to disconnect/remove a project or a github installation, post connection/installation?

You can stop following it, _or_ edit the settings on GitHub for the app installation to remove or reconfigure. We'll provide a link to configure existing repositories installed on that application.

> 3. Once you've connected a project, what has changed about the UI? What can you now do on Code Corps that you couldn't do before?

This issue doesn't go into much depth on that, but it will allow projects to have issues and issue comments on GitHub synced to tasks and task comments on Code Corps, and vice versa. This way your existing community on GitHub doesn't lose out just because some people are using Code Corps to do most of their PM and organizational work, and Code Corps can be used to track things coming in from GitHub. Tasks on Code Corps then can be connected up to a GitHub repository, or they could be unrelated to one (for example, a conversation about graphic design work might not best be suited for GitHub).

**Comment by JoshSmith** [comment]
Reposting from another PR:

We may need to split out our App's webhooks from user OAuth webhooks. This is because we appear to need _both_ the App and OAuth to do all the things on behalf of a user that we'd like to do. How we respond to each is thus likely to be different, and each app should likely have different webhook URLs for a cleaner separation of behavior.

For now, we may want to just progress with a `GithubEventsController` and two separate URLs, and simply record the source (App vs OAuth) depending on that.

I've tested out the integration with the App and certain endpoints are just altogether missing when doing something on behalf of a user with the App. That means we'll need a fallback.

Although well outside the scope of this PR, I'd like to take a moment to quickly explore the fallbacks, just for our own reference later. We can expect, when posting/editing an issue or comment, to:

- check first if the user has a GitHub account
- check the type of event
- check the GitHub user's integrations (App and OAuth), and their permissions

For example, if a user does not have a GitHub account, we'd need to post the issue as the `code-corps` App bot. If they did have one, we'd see if the event can be done by the App or needs to fall back to the integration. The App provides nicer feedback in GitHub's UI, but not all endpoints are available for us yet. So we may then need to fall back onto whether the user has connected with OAuth or the App. This latter part may be simplified if we can spend some more time thinking about what it means for someone to "connect with GitHub."

**Comment by JoshSmith** [comment]
@begedin we haven't updated this tracking issue in some time. Should we close this, or check some things off, or what? Not sure I feel that this is very relevant, and the milestones are doing the work of organizing what's left IMO.

**Comment by begedin** [comment]
There are some factors related to the `UserGithubAppInstallation` mentioned here that you may want to revisit, since you're more familiar with the concept. I'm hoping these are resolved successfully with the introduction of the user authorization scope on the `GithubAppInstallation` `index` action.

Basically, does reimplementing the index action as

- make a github request for current user's installations
- get github ids off of the response
- find and return only local installation records with those github ids

Completely resolve the problem of figuring which github app installations a user is able to access, or are there things I didn't account for?

**Comment by begedin** [comment]
@LennonR I'm moving your tracking ideas into a separate issue. 

@JoshSmith I believe this umbrella issue is in a good enough spot to be closed.

**Comment by JoshSmith** [comment]
@begedin my big concern now is that we write some of the big picture "how it works" in documentation somewhere, since that's spread across the client and server and not, I think, easily explained in summary form for a contributor to step into and explore.
