### ISSUE TITLE
Add Admin UI for project approval

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#1575]
# Problem

We need an Admin UI to view projects and approve them

## Subtasks
- [x] Add projects tab
- [x] Lists all projects, each linking to their show page
- [x] Unapproved projects have an "approve" button
