### ISSUE TITLE
Speed up CI builds

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/code-corps-ember#419]
This will serve as a master Issue for optimizing our build/testing process.
# Problem

Circle CI builds take a long time, usually 3 minutes, to complete. This is largely due to running `npm install` every time a build is running.
# Solutions

An optimization to take advantage of parallelism would help this, which can be done through`ember-exam`, which replaces the `ember test` sequence with a functionally similar method that uses concurrency.

There isn't any "official" support for this, but there are several workaround to prevent npm from making network requests before checking the cache, with the main npm discussion [here](https://github.com/npm/npm/issues/2568) which is what the npm foundation uses in their CI environment.
## Subtasks
- [x] Implement ember-exam and add it to the circle build config file
- [x] Implement parallel building through ember-exam
- [x] Edit documentation to reflect testing changes
- [x] Implement ember-exam in Circle CI with ember-try
- [x] #371 
- [ ] reduce npm install time by relying on cache unless there is a newer version available (--cache-min-infinity SHOULD do this, but didn't in initial testing)
## References

Ember-exam: https://github.com/trentmwillis/ember-exam

--cache-min Infinity: http://blog.cloudoki.com/npm-features-and-quirks/

**Comment by JoshSmith** [comment]
@rileytaylor what's the status of `ember-exam`? Anything I can do to help unblock that and get a PR in?

**Comment by rileytaylor** [comment]
I haven't had a chance to sit down on it, however I believe I have it added and set up for running in three threads. I need to test it. I have a chunk of time I can work on it right now and I'll update you shortly!

**Comment by JoshSmith** [comment]
@rileytaylor I'm going to close (even though builds are slow) since this is relatively outdated now (we use `yarn`, for example).

**Comment by rileytaylor** [comment]
Totally agreed!

**Comment by JoshSmith** [comment]
@rileytaylor I have opened #1083 and #1084 as follow-up tasks.
