### ISSUE TITLE
Increase Documentation around Onboarding/Outreach

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/code-corps-ember#423]
# Problem

Getting people started on the project is difficult as there is a lot to digest. We don't have a real "Onboarding Plan", and while the nature of long-distance coding will require a lot of hands-on time, having some solid introduction documentation and information around common problems would be helpful, especially in regard to how things work with our project.

This is a very open issue. I encourage editing of this task list, preferably if we have discussed it in comments here or on slack.

# Solution

I see two outputs of this: 

1. Several files in the `Docs` folder that discuss setup, common issues, resources to go to on Ember, Node.js, and the other things we use, how to use git, how to get the backend running, and more. 
2. A checklist of sorts for core team/onboarding people to use to get people going.

We've considered a wiki for this, but initially/permanently working via git with versioning, pull requests and commenting will be incredibly helpful. Plus everyone will have the documentation locally when they clone, and most (Sublime, Atom, VS Code for sure) have Markdown previewing. 

## Tasks

- [x] Installation
- [x] Rundown of Git and goto resources
- [x] Configuring the Backend (this should mostly be a link to the proper documentation on the Phoenix repo)
- [x] Squashing/Rebase
- [x] Our development workflow
- [x] Common problems
- [x] Guide to documentation via YUIDoc

## Long-term Tasks
- [x] Par down the readme by keeping it a summary and linking to documentation we create
- [x] Cross-reference our documentation as much as possible

**Comment by ravaan** [comment]
Hey, I wanted to contribute as a part of the Hacktoberfest, any heads up where should I begin with?

**Comment by JoshSmith** [comment]
Hey @ravaan! Thanks for coming to help. I would maybe consider focusing on the first checkbox here (and opening it as a separate issue). If you want to come into our Slack (http://slack.codecorps.org) then one of us would be happy to help with some additional direction.

**Comment by rileytaylor** [comment]
Most of the documentation is now complete. Closing this issue and compiling the remaining low priority documentation things into a new issue for tackling/disregarding at a later time.
