### ISSUE TITLE
Add ember-i18n

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#448]
# Problem

We want to avoid duplication of content and eventually allow for internationalization.
## Subtasks
- [ ] Add i18n
- [ ] Deduplicate content in head tags
- [ ] Research which parts of templates could be i18n-ed

**Comment by LBKinson** [comment]
hey @JoshSmith, would love to contribute on this. I have a fair amount of experience with the ember-i18n addon. Can you clarify what "deduplicate content in head tags" means? I'm not seeing double info.

For templates: all hard coded verbage can be internationalized. I'll submit a PR for just one page so you can see and then I can move forward on converting all templates if that looks good.

**Comment by JoshSmith** [comment]
@LBKinson it looks like what I meant by that is the duplication of `content` in the application route of say `meta-description` and `meta-og-description`, among others. Those could certainly be candidates for other hard-coded verbiage that's removed.

**Comment by LBKinson** [comment]
Ohhh gotcha. Where `meta-description` and `meta-og-description` have the same content. Yes, those can definitely be replaced by one line item in the translation file.

**Comment by JoshSmith** [comment]
Yeah, I'd almost forgotten what I meant, but that's certainly what I was hoping!

**Comment by JoshSmith** [comment]
Per @LBKinson on the (now-merged) PR, we still need to do the following:

Needs:
- [ ] translations on all other templates
- [ ] translations on any dynamically generated messages (i.e. errors) within routes and components
- [ ] UI design for a user to change their locale (example below)

<img width="262" alt="screenshot 2016-10-26 22 39 58" src="https://cloud.githubusercontent.com/assets/4722967/19755826/33b427cc-9bcd-11e6-9c4d-577532e241f6.png">
<img width="288" alt="screenshot 2016-10-26 22 40 08" src="https://cloud.githubusercontent.com/assets/4722967/19755831/35d5bf16-9bcd-11e6-8ccf-23fb20f7ba09.png">
