### ISSUE TITLE
Add donations Stripe OAuth workflow for projects

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#468]
# Problem

We need to add this workflow to the Ember app https://projects.invisionapp.com/share/RT8PS9FK2#/screens
## Subtasks
- [ ] Create a `/project-slug/donations` page
- [ ] By default the page will start off with a "Connect with Stripe" button if it's not yet attempted one (i.e. project doesn't have some related subscription or is not waiting on an account)
- [ ] Connect with stripe button is rendered with the URL to start OAuth process for organization
- [ ] Need to be able to take OAuth redirect code `https://example.com/connect/default/oauth/test?scope=read_write&code=AUTHORIZATION_CODE` and `POST` it to the API along with `state`
- [ ] The server takes the JWT from `state` and the `code` provided by Stripe and attempts to get an access token; we redirect to the organization's donations page
- [ ] Present a button to refresh to refresh the page and see if account has been activated yet with Stripe
- [ ] Show add goals UI when done
## References

Progress on: https://github.com/code-corps/code-corps-api/issues/10

**Comment by JoshSmith** [comment]
We can get the `state` and `code` like this:

```js
export default Controller.extend({
  queryParams: ['code', 'state'],
  code: null,
  state: null
});
```

**Comment by JoshSmith** [comment]
Then it's just a matter of trying to create the Stripe account:

```js
export default Route.extend({
  model(params) {
    this.get('store').createRecord('stripe-account', {
      code: params.code,
      state: params.state
    });
  }
});
```
