### ISSUE TITLE
Add workflow to start accepting donations

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#469]
# Problem

We need to add the rest of the UI to start accepting donations. Starts here: https://projects.invisionapp.com/share/RT8PS9FK2#/screens/191325346
## Subtasks
- [x] When the account does not yet have any fundraising goals, show add goal UI (custom amount, description)
- [x] Allow users to edit their goals
- [x] Allow users to add a new fundraising goal
- [ ] When one goal has been added, allow account to turn on donations (tells API to create Stripe plan for that account) - #670
## References

Progress on: https://github.com/code-corps/code-corps-api/issues/10

**Comment by JoshSmith** [comment]
@begedin still not sure the best way to tell the API to actually turn donations on. Should that be what creates the Stripe Plan for that account?

**Comment by begedin** [comment]
Good question. 

That would likely be the most straightforward to implement.

Other choice is a literal field on the project table that we set to true. We would still have to create a plan in that case, though. Maybe it doesn't have to be a restful action? 

Maybe we simply post to a `/projects/:id/enable_donations` endpoint and then that endpoints does what it needs to do?

**Comment by JoshSmith** [comment]
I think creating `StripePlan` is best, so let's go with that. It makes the most sense, IMO.

**Comment by JoshSmith** [comment]
Closing in favor of #670.
