### ISSUE TITLE
Add a donation goal component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#470]
# Problem

As seen on https://projects.invisionapp.com/share/RT8PS9FK2#/screens/191325346 and https://projects.invisionapp.com/share/RT8PS9FK2#/screens/191325348
## Subtasks
- [ ] Have a field for adding an amount
- [ ] Have a field for adding a description
- [ ] Create goal button when it's new
- [ ] Edit link once saved
- [ ] When editing, can cancel or save goal
## References

Progress on: #469

**Comment by JoshSmith** [comment]
Closed by #634.
