### ISSUE TITLE
Add donation progress component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#471]
# Problem

The donation progress component will be a sub-component of the project's donation UI seen here https://projects.invisionapp.com/share/SP8PSQGNM
## Subtasks
- [ ] Take in the project's current goal
- [ ] Display the monthly amount for the current goal
- [ ] Calculate the percentage for the current goal
- [ ] Display the percentage for the current goal
- [ ] Display a progress bar using the percentage amount
- [ ] Display the current goal's description
