### ISSUE TITLE
Add donation project sidebar component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#472]
# Problem

We need to add the component seen on https://projects.invisionapp.com/share/SP8PSQGNM, https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191333611, and https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191332617
## Subtasks
- [ ] Show the sub-component of donation progress #471 
- [x] Show success state with amount you give each month: `You give $10 each month`.
- [x] Display "Become a donor" button by default
- [x] Clicking the "Become a donor" button slides down to reveal donation UI
- [x] Four buttons: "Donate $10", $15, $25, $50
- [x] Custom amount per month field that only accepts integers
- [x] Continue button that takes the amount and passes it onto the next page `/projects/donate?amount=number`

**Comment by JoshSmith** [comment]
We can use `accounting.js` for changing the dollar numbers into well-formatted cents integers to post to the API. http://openexchangerates.github.io/accounting.js/

**Comment by begedin** [comment]
I'm thinking we have multiple components here, each of which renders based on what the model state is.

* If we have no donation model loaded, then we render  `{{donations/become-a-donor}}`
* If we have a donation model, but it's a new record, means we just clicked "become a donor", so we render `{{create-donation}}`
* If we have a donation model and it's a persisted record, mean we already donated, so we render `{{donation-item}}` or something.

**Comment by JoshSmith** [comment]
@begedin do you mean an active subscription in your last point?

**Comment by begedin** [comment]
Somehow edited your reply instead of replying myself. 

Really, I mean "active subscription" on all 3 points. I'll correct.

**Comment by JoshSmith** [comment]
Closing in favor of #679
