### ISSUE TITLE
Add edit donation amount component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#474]
# Problem

As seen on this screen: https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191332630

## Subtasks
- [ ] Show current amount
- [ ] Edit link changes UI
- [ ] Edit UI has same buttons and custom amount, and continue button as https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191333611
- [ ] Hitting "Continue" changes back to new current amount

**Comment by JoshSmith** [comment]
I'm not sure this needs to be in the first version. We can punt on this and implement later. Let's just remove the "Edit" link for now inside of it.

You disagree @begedin?

**Comment by begedin** [comment]
Not really. I mean, it's going to be a tad annoying for some, but not hard to fix later.

**Comment by JoshSmith** [comment]
Right, back button is still possible for now. Let's be strict with ourselves by what is "minimum viable." If you see something in spec that violates that, then call me out on it.

**Comment by laveshaparker** [comment]
Hi all! I'm not able to assign this to myself, but I'm going to take a look at it as part of the MakeADiff workathon.
