### ISSUE TITLE
Add page for /project/donate?amount=number

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#475]
# Problem

When hitting the page for `/project/donate?amount=number` it should look like this https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191332630
## Subtasks
- [x] Show #476 project logo, title, and description
- [x] Show #474 edit amount UI
- [x] Show #473 add card UI

Moved this one to #669. I think it's not MVP (@begedin)
- Show select card UI (you have at least one card)

**Comment by rileytaylor** [comment]
@JoshSmith should we take this one out of the donations project and close this issue?

**Comment by JoshSmith** [comment]
Closing because this is mostly handled.
