### ISSUE TITLE
Finish thank you page

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#477]
# Problem

We need a thank you page as seen here: https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191332621

## Subtasks
- [x] Show #476 project header
- [x] Show thank you icon and text
- [x] Have a link back to the project
- [ ] Add src to the icon image
- [ ] Change alt text to be about the success
- [ ] Match text color/size/spacing everywhere
- [ ] Blocked by #678 – Show 12 random team members (who have actual photos, not the default icons)

**Comment by JoshSmith** [comment]
I removed the "photos of contributors" to make this shippable more quickly.

**Comment by begedin** [comment]
Mostly solved in #668 

All that's left is to add the icon src. Will update original description

**Comment by WenInCode** [comment]
I'll take on finishing up this task

**Comment by JoshSmith** [comment]
Closed by #786.
