### ISSUE TITLE
Fix issues caused by removing many-to-many relationships

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#489]
# Problem

We had some bugs arise from the removal of some many-to-many relationships in Ember. While a good idea generally, it looks like tests gave false positives.
## Subtasks
- [ ] Step through mirage models and compare to actual models
- [ ] Force test failures
- [ ] Write regression tests to catch failures
- [ ] Fix failures

**Comment by JoshSmith** [comment]
We also really want to figure out how to rewrite so I can do some sort of equivalent syntactic sugar to `project.skills` instead of doing what I've had to do down at a component level to make this fix work in https://github.com/code-corps/code-corps-ember/pull/488#discussion_r80818287.

You'll see in that comment that doing this:

```javascript
  projectCategories: Ember.computed.mapBy('project.projectCategories', 'category'),
  projectOrganizationMembers: Ember.computed.mapBy('project.organization.organizationMemberships', 'member'),
  projectSkills: Ember.computed.mapBy('project.projectSkills', 'skill')
```

...is really duplicative and is happening in a _component_. That's even worse, and seems like something we should really be avoiding.

**Comment by JoshSmith** [comment]
As I said in the comment above:

> As an example, inside of a project's page may show its categories and skills. May use the same thing on the contributors page when approving a new contributor to see the overlap with their categories/skills and the projects'.

It's entirely possible the move to eliminate many-to-many relationships was premature. I'm not sure about this yet, but it does seem as though we lost something without a well considered replacement.
