### ISSUE TITLE
Add ember-autoresize when it no longer fails in phantomjs

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#490]
# Problem

It appears that `ember-autoresize` is having some issues due to some lifecycle changes in Ember.
## Subtasks
- [ ] Check the issue until fixed
- [ ] Re-add `autoresize=true` to the `editor-with-preview` component
- [ ] Uncomment tests that test for height changes
## References

https://github.com/tim-evans/ember-autoresize/issues/40
