### ISSUE TITLE
Many components call set on destroyed objects

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#508]
# Problem

Take our async button components, which are on a page that could be navigated past before the response for the async button behavior would finish.

In the event the user navigates elsewhere, the button component itself may attempt to call `set` on itself, but it is now destroyed.

We should identify instances of calling `set` with asynchronous behavior, and fix it, perhaps by using `ember-concurrency` in some fashion.
## Subtasks
- [ ] Evaluate best approach for handling this (`ember-concurrency`? simple guards?)
- [ ] Identify instances where we call `set` on destroyable objects with async behavior
- [ ] Write regression tests
- [ ] Implement working code to make tests pass

**Comment by begedin** [comment]
I've never gotten around to dealing with this, though I have encountered the issue occasionally. 

I personally think we shouldn't strive too hard for a catch-all fix here.

If something like this is happening, it's likely because our code is trying to do something it shouldn't, or when it shouldn't, so I think we should identify these individual cases and see how to fix them specifically. 

http://stackoverflow.com/questions/25141822/uncaught-error-assertion-failed-calling-set-on-destroyed-object

It's possible that in some of these, a catch all solution is the way to go, but we should Identify the problems first, before deciding on the solution.

**Comment by JoshSmith** [comment]
I don't see many of these happening right now. We should evaluate on a case-by-case basis.
