### ISSUE TITLE
Access token could not be refreshed - server responded with .

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#510]
# Problem

After sitting idle for some time, Ember attempts to get a refresh token from the server. Only problem? No such endpoint exists.

![](https://d3vv6lp55qjaqc.cloudfront.net/items/1x2c3V0v1Y3G2F2J0p2z/Screen%20Shot%202016-09-29%20at%209.59.26%20AM.png?X-CloudApp-Visitor-Id=1336043&v=386b7cf5)

## Subtasks
- [x] Need to figure out what the simple-auth-token library is doing
- [x] Come up with a solution
- [x] If necessary, open up an API issue

**Comment by JoshSmith** [comment]
https://sentry.io/code-corps/code-corps-ember/issues/164475178/

**Comment by JoshSmith** [comment]
I've got this!
