### ISSUE TITLE
Use ember-

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#511]
# Problem

Computed properties are good, but the implicit two-way binding is _bad_. Stefan just introduced `ember-improved-cp`, which makes CP's read-only.

https://github.com/stefanpenner/ember-improved-cp

## Subtasks
- [ ] Identify all places where we could use this (maybe `git grep computed`?)
- [ ] Submit a pull implementing the changes
- [ ] Verify that nothing has broken

**Comment by fpapado** [comment]
@JoshSmith I can give this a shot over the weekend! The develop tests are still throwing due to the "pretender instances [...]" issue raised on Slack, but I can work on putting together a list of places for now.
