### ISSUE TITLE
Add catch-all routes for 404 to fix UnrecognizedURLError

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#553]
# Problem

When navigating to a URL that does not exist, Ember sends an `UnrecognizedURLError` to Sentry: https://sentry.io/share/issue/38323734312e313634363039343439/

https://guides.emberjs.com/v2.8.0/routing/defining-your-routes/#toc_wildcard-globbing-routes
## Subtasks
- [ ] Write failing test
- [ ] Create a 404 page route
- [ ] Break `error-wrapper.hbs`'s 404 error out into a separate component to use same styling
- [ ] Fix `.button.on-solid` colors in CSS

**Comment by JoshSmith** [comment]
https://sentry.io/code-corps/code-corps-ember/issues/164609449/

**Comment by JoshSmith** [comment]
https://sentry.io/code-corps/code-corps-ember/issues/165341733/

**Comment by JoshSmith** [comment]
Also would look at http://stackoverflow.com/a/25558348/373496

**Comment by filipecrosk** [comment]
@JoshSmith is it really necessary to create a component for this 404 page? Any plans to use this in another place?

**Comment by JoshSmith** [comment]
@filipecrosk there's already a 404 component so we can reuse that one. It's already in use elsewhere (catching errors from the API that are a 404).

**Comment by JoshSmith** [comment]
Whew. The issue here is NOT on the Ember side.

Basically the API is correctly returning a `404` to Ember. The problem is that the API _also_ is not respecting CORS headers, and not returning the allowed origins. This is where our error arises.

We'll need to handle this in the API. Creating an issue there and closing this one.

**Comment by begedin** [comment]
https://sentry.io/code-corps/code-corps-ember/issues/307723158/

**Comment by begedin** [comment]
Reopening this because the `UnrecognizedURLError` still fires when someone attempts to hit a non-existent route in our app. For example, we've been getting it for `/:organization_slug/:project_slug/pots/:post_number`, which is the old url when we've been using the term "post" instead of "task".

Right now, if we attempt to hit such a route, we just get a blank screen.
