### ISSUE TITLE
Add ember-cli-code-coverage

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#564]
# Problem

Add some code coverage reporting. https://github.com/kategengler/ember-cli-code-coverage
## Subtasks
- [ ] Add the reporting
- [ ] Make the reporting work with Circle and Coveralls
- [ ] Add the Coveralls badge to the README
