### ISSUE TITLE
Use ES6 template strings consistently

### ISSUE THREAD

**Issue by sbatson5** [code-corps/code-corps-ember#584]
# Problem

With babel.js and access to a lot of ES6 goodness, we can now use template strings for string concatenation.  For example, we leverage them in some files:
https://github.com/code-corps/code-corps-ember/blob/develop/app/components/error-formatter.js#L39

Yet use JS concatenation in other places:
https://github.com/code-corps/code-corps-ember/blob/develop/app/components/landing-subsection.js#L18
## Subtasks
- [ ] Identify all places with old string concatenation
- [ ] Update to use template strings
- [ ] Update Styleguide (possibly add something to the linter?)

**Comment by sbatson5** [comment]
And yes, this is me volunteering again 😄

**Comment by JoshSmith** [comment]
👍 go for it!

**Comment by sarupbanskota** [comment]
@sbatson5 @JoshSmith don't mean to step on your toes, but with https://github.com/code-corps/code-corps-ember/pull/499 we're introducing ESLint. 

With the `--fix` option, ESLint automagically looks after string conversions. 

Just saving you some effort there :-)

**Comment by sbatson5** [comment]
No toe stepping at all @sarupbanskota 😛 .  Excited for ESLint and code consistency!
