### ISSUE TITLE
Fix code styling offences throughout the project

### ISSUE THREAD

**Issue by sarupbanskota** [code-corps/code-corps-ember#594]
# Problem

Through $499 and #593, we introduced `eslint` and `ember-suave`. The changes were made in a manner that the current state of the project stays green. Now it's time to improve styling, so we gotta attack each of the rules that have been turned off, fix them, and remove them off the list.

The full list is outlined below.

## Subtasks
- [ ] comma-dangle
- [ ] spaced-comment
- [ ] object-shorthand
- [ ] quotes
- [ ] brace-style
- [ ] max-statements-per-line
- [ ] keyword-spacing
- [ ] no-var
- [ ] space-in-parens
- [ ] generator-star-spacing
- [ ] indent
- [ ] space-infix-ops
- [ ] operator-linebreak
- [ ] object-curly-spacing
- [ ] dot-notation
- [ ] no-console
- [ ] prefer-template
- [ ] space-before-function-paren
- [ ] comma-spacing
- [ ] no-multiple-empty-lines
- [ ] camelcase
- [ ] no-trailing-spaces
- [ ] key-spacing
- [ ] new-cap
- [ ] one-var
- [ ] space-before-blocks
- [ ] ember-suave/no-const-outside-module-scope
- [ ] ember-suave/no-direct-property-access
- [ ] ember-suave/prefer-destructuring
- [ ] ember-suave/require-access-in-comments
- [ ] ember-suave/require-const-for-ember-properties

## How to fix

1. On the [ESLint file](https://github.com/code-corps/code-corps-ember/blob/develop/.eslintrc.js), remove any rule that you're interested in fixing.
2. This will lead to errors corresponding to offences on that rule.
3. Once you fix them, you may start a new PR 

Let's get this going!

**Comment by idelairre** [comment]
I can work on this during the day (its 1:20am where I'm at). I should be able to take care of them all at once.

**Comment by sarupbanskota** [comment]
@idelairre yay, even better, as I'm going to have a busy week thanks to $DAYJOB. 
Just be sure to keep a separate commit per offence, for easy reviewing.

**Comment by idelairre** [comment]
hey, so in order to get the "no-var" rule to pass I need to change every `var` into a `let` or `const`. `const` is used periodically throughout the project but `let` is preferred even if the variable isn't reassigned. Should I add the "prefer-const" rule so there are clear terms on when to use `const` or just change every `var` into a `let`?

**Comment by JoshSmith** [comment]
I'm in the prefer let camp.

**Comment by sarupbanskota** [comment]
@idelairre I prefer having `const`, but I'm new to this project, so no preferences :-)

Btw, if you're picking up a given rule, could you please leave a message here, so that anybody else who would like to pick up another rule could take up others?

**Comment by idelairre** [comment]
gotcha, I'm gonna go with @JoshSmith on this one since this is an easy fix later. 

So far I have comma-dangle, spaced-comment, object-shorthand, quotes, max-spaces-per-line, and keyword spacing done. Can I go ahead and claim the rest and have this be one big PR?

**Comment by JoshSmith** [comment]
@idelairre you've got it. Did you do the rest in that PR submitted?

**Comment by idelairre** [comment]
The only things left are no-console, camel-case, new-cap, and require-access-in-comments.

A few notes:
- I think enforcing camel-case would break the app since the snake-cased properties are coming from the api
- I wasn't comfortable deleting the console.error entries since one or two of them had comments
- new-cap was throwing because of jQuery in one test. I'm sure there is a clever way around this or maybe we could just ignore that rule in those instances
- I have to study the spec for require-access-in-comments to understand how to document correctly, then I can have a go at it.
