### ISSUE TITLE
User Documentation Improvement

### ISSUE THREAD

**Issue by rileytaylor** [code-corps/code-corps-ember#601]
# Problem
#423 solved most of our user documentation needs. This issue includes the lower-priority ideas for improving documentation. This is meant to be more of a living list, collecting thoughts from new users as we onboard more developers, as well as collecting more common issues that need to be added to our 'Common Issues' section.
## Possible Improvements
- [ ] Mention and link to discussion about SSH Key's (and asking nicely to use a newer type... NOT rsa) since that is needed by one of our npm packages. In particular, this might mention the win32 port of `open-ssh` for windows users
- [ ] Forking instructions, github-flow guide (#326)
- [x] Greenkeeper steps/process (see #458)
- [ ] Detailed YUIDoc documentation steps, We could use somewhere to collect decisions on certain items, such as when to differentiate between `Ember.object` and just `object`, etc.
- [ ] More discussion of running the backend at the same time, mention to ask questions in the api channel on slack if there are problems getting it running
- [ ] Test structure in styleguide (see #330)
- [ ] CSS styleguide topic that includes BEM (see http://getbem.com and http://cssguidelin.es/#bem-like-naming)

## Common Issues to mention

(nothing so far!)

**Comment by JoshSmith** [comment]
Closing as a bit outdated.
