### ISSUE TITLE
Add cancel link to the credit-card component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#677]
# Problem

We need to add a cancel link centered just below the "Add Card" button on the `credit-card` component.

## Subtasks
- [ ] Ensure link only renders when this is _not_ the first card being created
- [ ] Make the cancel link return you to the card list of existing cards
- [ ] The card form should not have old card information retained if you press cancel
- [ ] Should have a confirmation alert if any of the fields are filled out, so you don't lose all your work
- [ ] Write tests

**Comment by WenInCode** [comment]
I can take this one on. One quick question, is there any way to add mock cards in development?
<img width="486" alt="code_corps" src="https://cloud.githubusercontent.com/assets/5448834/20335260/503bba2a-ab7e-11e6-84e6-a0654b238c77.png">

**Comment by JoshSmith** [comment]
@WenInCode if you go back to zero cards, then the cancel link is a confusing UI. If there are zero cards, there shouldn't be a cancel link.

You can just pass in some fake data in the template, I think.

**Comment by WenInCode** [comment]
good stuff - thanks

**Comment by WenInCode** [comment]
> @WenInCode if you go back to zero cards, then the cancel link is a confusing UI. If there are zero cards, there shouldn't be a cancel link.

Right, so this should actually be

> Ensure link only renders when this **is not** the first card being created

right?

**Comment by JoshSmith** [comment]
@WenInCode Yes, sorry. Grammars.
