### ISSUE TITLE
Add volunteer headshot component

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#678]
# Problem

On this page we have photos, name, and a randomly selected role of the user. https://projects.invisionapp.com/share/SP8PSQGNM#/screens/191332621

## Subtasks
- [ ] Show user's photo
- [ ] Show the user's name, or if blank, their username (see an example of this in the profile sidebar component – should maybe extract out elsewhere as a helper)
- [ ] Show one role for the user (randomly selected)

## References

Progress on: #
#477

**Comment by WenInCode** [comment]
@JoshSmith does this task include putting it on a page, or just building out the component (right now I assume the latter)

**Comment by JoshSmith** [comment]
@WenInCode ideally putting it on the `/thank-you` page, but we can start with just the component and make acceptance portion a follow-on task.

**Comment by JoshSmith** [comment]
@WenInCode #477 is actually more important I think, and that can be said to be done before this one is. This is _not_ blocking that, even if it says that it is.

**Comment by WenInCode** [comment]
@JoshSmith are we wanting to list all contributors (`organization-members`) or randomly select a subset?
