### ISSUE TITLE
Remove coalescing from stripe- models

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#680]
# Problem

All of our `stripe-` models should be written so that they do not coalesce records on fetch using `ember-data`. Records will need to be individually fetched.

## Subtasks
- [ ] Write test for the coalescing behavior
- [ ] Implement the right behavior
- [ ] Add endpoints to Mirage that mirror this behavior; ensure no `index` endpoints in Mirage
