### ISSUE TITLE
Set up mirage to work in a development environment.

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#692]
# Problem

Having mirage configured so we can use it as a sort of "mock API" in the development environment would significantly lower the barrier of entry for contributors and allow them to work on the client without needing to setup the API

## Subtasks

- [ ] Use the current mirage API config as a base for setting up mirage in development
- [ ] Extend config if necessary
- [x] Seed the configuration with mock data - API-side seeds can serve as a template
- [x] Put the feature behind a flag, similar to how we handle remote development right now

**Comment by sbatson5** [comment]
What would the plan be for keeping the API and mirage mocks in sync? I can foresee issues when updating models on the backend and having our mirage fall out of sync, especially if the `testConfig` for mirage is different for our testing environment.

**Comment by JoshSmith** [comment]
I'm not sure what the best way of handling this would be. Let me ask Sam, if he has a moment, what his recommendation would be here.

**Comment by JoshSmith** [comment]
@begedin @sbatson5 I'm not sure if there's any need to actually extend the Mirage config at all. The config is the config. What you use in testing would work in development.

We really only need the seeds and the flag.

@sbatson5 we already risk a chance that the Mirage API is out of sync with the actual API. We have no acceptance testing that fully integrates the backend API with this Ember app.

My ideal world is that we one day use API Blueprint and something like Dredd to generate testing hooks for both the API _and_ the Ember app, so that our Ember acceptance tests and our Elixir controller tests are bound to the contract specified in the API documentation itself.
