### ISSUE TITLE
Rewrite integration tests with page objects

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#697]
# Problem

We need to rewrite integration tests to make use of page objects.

## Subtasks
- [x] Identify tests that are missing page objects
- [x] Create issues for all of those
- [ ] Submit PRs for each

## References

Related to: #141
