### ISSUE TITLE
Finalize logic to "enable donations"

### ISSUE THREAD

**Issue by begedin** [code-corps/code-corps-ember#709]
# Problem

We should finish the last parts of enabling donations for a project

## Subtasks
- [x] If the project has no `stripeConnectAccount` associated, stripe connect button is visible
- [x] Stripe connect button works and the end result is that it creates a `stripeConnectAccount`
- [ ] If there is a stripe connect account and the project has donation goals, but no associated `stripeConnectPlan`, the "turn on donations button" is visible 
- [ ] If there is no plan or donation goals, a message indicating donation goals are needed is show instead of the button
- [ ] clicking the button creates a plan for the project
- [ ] if there is a plan, a message indicating donations are active is visible
