### ISSUE TITLE
Only show donation goal progress when donations are active on the project

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#791]
# Problem

Right now we don't have any tracking of the `donations-active` attribute rendered from the Project. This should be used for showing the goal progress.

## Subtasks
- [ ] Show goal progress only when donations-active is true
- [ ] Add model tests
- [ ] Add acceptance tests
