### ISSUE TITLE
Add rendering of split credit card numbers in input when typing

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#799]
# Problem

We should add an ember-fied version of https://github.com/stripe/jquery.payment#fnpaymentformatcardnumber (minus the jQuery). Can use this for inspiration.

https://github.com/stripe/jquery.payment/blob/master/lib/jquery.payment.js#L224

## Subtasks
- [ ] Includes a space between every 4 digits
- [ ] Restricts input to numbers
- [ ] Limits to 16 numbers
- [ ] Supports American Express formatting
