### ISSUE TITLE
Organization memberships don't load correctly on sign in

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#824]
# Problem

A user's organization memberships do not appear to refresh on sign in, and load in inconsistently at other times.

You can see this when:

- Signing in and trying to join a project; the button will not change state because the memberships have not updated or computed
- Signing in as an organization admin and not seeing the right tabs on a project

## Subtasks
- [ ] Determine what is causing this issue
- [ ] Write a regression test that catches up
- [ ] Fix the issue

**Comment by noslouch** [comment]
got a failling test for this
