### ISSUE TITLE
Markup and styles for upcoming task UI

### ISSUE THREAD

**Issue by marineb** [code-corps/code-corps-ember#841]
# Problem

- hardcode any component you’re working on
- test it out without having whole models instantiated
- CSS class naming should go as follow, following BEM conventions. 

`task-board`

`task-list`
`task-list__title`

`task-card`
`task-card__title`
`task-card__number`
`task-card__type`
`task-card__time`

And the modifiers could be: `--inbox`, `--backlog`, `--progress`, `--done` (e.g. `task__card--done`)

## Subtasks
- [ ] `task-board` (holds the four columns, never taller than window, scrolls left/right to show columns)
- [ ] `task-list` (the column)
- [ ] `task-card` (the individual task)

## References

Progress on: [#2](https://github.com/code-corps/design/issues/2) (design repo)

**Comment by JoshSmith** [comment]
I think we might want components that are something like:

- `task-list-container` (holds the four columns, never taller than window, scrolls left/right to show columns)
- `task-list` (the column)
- `task-card` (the individual task)

We can implement all of these components roughly independently from each other.

**Comment by JoshSmith** [comment]
@marineb might be useful to break these out into separate issues and use this as sort of a journey issue.

**Comment by marineb** [comment]
Ok. That sounds great. Thank you. I'll start creating new sub-issues as I start tackling them.

**Comment by JoshSmith** [comment]
@marineb may consider doing them all at once so people can tackle them independently if needed. Massively parallelizable workload is ideal if we can swing it.

**Comment by rlueder** [comment]
Quick suggestion on naming the new components and also styling them following the BEM conventions:

task__board (from Kanban board)
task__column
task__card

And the modifiers could be: --inbox, --backlog, --progress, --done (e.g. task__card--done)

Since columns might eventually be renamed it might make sense to have the cards have the modifiers instead of the columns. Just a thought. :)

**Comment by JoshSmith** [comment]
@rlueder what do you think about `list` over `column`. This doesn't tie us to an implementation (vertical vs horizontal) but rather more of a data structure (ordered list).

**Comment by rlueder** [comment]
Or (hah this is so true [Naming CSS Stuff is Really Hard](https://seesparkbox.com/foundry/naming_css_stuff_is_really_hard))

task-board
task-board__title

task-column
task-column__title

task-card
task-card__title
task-card__number
task-card__type
task-card__time

**Comment by JoshSmith** [comment]
Don't think `task-board` needs a title, but approve of thinking around others except the `-column` per comment above.

**Comment by rlueder** [comment]
@JoshSmith was posting my change of mind as you were writing yours. :)

I can see list working as well, though I guess I'm thinking more in terms of the common terms used in agile boards: board, column, cards, and swim lanes or just lanes (those would be horizontal).

I think it's a valid idea but I can't really see the board flipping on its axis, horizontal lists (or lanes) would be handy in the future though.

**Comment by JoshSmith** [comment]
I agree that the axis probably would not flip. I do think though that `swim lane` and `lane` are too methodology-specific and not as friendly for ESOL speakers. I think either `list` or `column` wins out, and prefer `list` since it matches closer to the `TaskList` object we're likely to have on the backend.

**Comment by rlueder** [comment]
Sounds good! let's not let semantics paralysis get to us! (btw I checked Trello and they use board, list and card) 👍

**Comment by marineb** [comment]
👍 Will update the issue summary.

**Comment by JoshSmith** [comment]
@rlueder http://talkingcode.com/podcast/episode-18-abby-covert/#06:38

**Comment by JoshSmith** [comment]
I think Trello using it is a strong point in its favor, since most people will look at this UI (rightly or wrongly) and think Trello and not "kanban".

**Comment by jasierragarcia** [comment]
**Task-board**

- [ ] create `task-board` component

- [ ]

**Comment by jasierragarcia** [comment]
**Task-board**

- create `task-board` component

- create `task-board.scss`

- need to import `task-board.scss` into `app.scss

- assign class name = `task-board` for `div` in `task-board.hbs`

- in `task-board.scss` give `task-board` class, properties of `border: 2px solid #CCCCCC;` &
 `height: calc(100% - 100px);`

**Comment by JoshSmith** [comment]
I'm going to close this since the other issues are tracking this more closely now.
