### ISSUE TITLE
Remove Stripe OAuth everywhere

### ISSUE THREAD

**Issue by JoshSmith** [code-corps/code-corps-ember#850]
# Problem

We're moving to managed accounts on Stripe and are no longer connecting accounts via OAuth.

To that end we need to remove anything Stripe OAuth related.

## Subtasks
- [x] Remove the `stripe-auth` adapter
- [x] Remove from the projects/settings/donations route
- [x] Remove from the projects/settings/donations template
- [x] Remove from the donations template
- [x] Remove the `oauth-stripe` route
- [x] Remove associated templates
- [x] Remove styles
- [x] Remove the Stripe connect button and styles
- [x] Remove routes from the router
- [x] Remove the oauth-stripe template
- [x] Remove the oauth-stripe-loading template
- [x] Remove the Stripe connect acceptance test
