### ISSUE TITLE
Create Model for Task-List

### ISSUE THREAD

**Issue by WenInCode** [code-corps/code-corps-ember#855]
# Problem
From the [corresponding API issue](https://github.com/code-corps/code-corps-api/issues/554)

> Currently, a project in code corps has many tasks. We need to create a new layer, 'task list', that allows ordered grouping of those tasks within a project. The task list should have the following properties:
> 
> * name: string
> * position: integer
> * tasks: has_many tasks
> * project: belongs_to project

We'll also need to create/update mirage models & endpoints

## Other model changes
**Project:**
- hasMany TaskLists

**Tasks:**
- belongsTo TaskList

## Subtasks
- [x] Create task-list model & mirage model
- [x] Update project & tasks models & mirage models
- [x] Create task-list mirage endpoint

## References
- [project model](https://github.com/code-corps/code-corps-ember/blob/develop/app/models/project.js)
- [project mirage model](https://github.com/code-corps/code-corps-ember/blob/develop/mirage/models/project.js)
- [task model](https://github.com/code-corps/code-corps-ember/blob/develop/app/models/task.js)
- [task mirage model](https://github.com/code-corps/code-corps-ember/blob/develop/mirage/models/task.js)
- [corresponding API issue](https://github.com/code-corps/code-corps-api/issues/554)

**Comment by WenInCode** [comment]
@JoshSmith let me know if I am missing something, or maybe have something too much. I'll likely get started on this tonight, need to touch some other work up first.

**Comment by JoshSmith** [comment]
@WenInCode would keep `tasks` on `project` still.

We also need to add `position` to `task`, I think.

**Comment by WenInCode** [comment]
@JoshSmith sure. Mind if I ask why we should keep tasks on a project? I understand that tasks do belong to a project, but if they are on a taskList, would that not be enough? Just curious.

**Comment by JoshSmith** [comment]
@WenInCode because we want to be able to do things in the future that don't require going through the intermediate relationship of the task list. The task list is a view into a project's tasks. But say I want to be able to do # autocompletion like GitHub. Or a search field for the tasks on a project. Maintaining that relationship lets us construct other such views into a project's task.
